# Generated by Django 3.1.4 on 2020-12-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('address_country', models.CharField(max_length=20)),
                ('address_city', models.CharField(max_length=20)),
                ('address_street', models.CharField(max_length=20)),
                ('address_house_number', models.IntegerField(max_length=3)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
